#!/bin/bash

echo 'Syncing files to server'
rsync --exclude=node_modules/ --exclude=aw/ -rave "ssh -i ~/.ssh/qnzl -A" * root@8.9.3.221:aw-sync;

echo 'SSHing in and restarting the server'
ssh root@8.9.3.221 -i ~/.ssh/qnzl "cd aw-sync && npm install && sudo supervisorctl restart aw-sync"

